// <auto-generated />
using System;
using MeliManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeliManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260616175117_AjusteFinalModelo")]
    partial class AjusteFinalModelo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("MeliManager.Core.Models.CuentaMeli", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaExpiracionToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaVinculacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cuentas");
                });

            modelBuilder.Entity("MeliManager.Core.Models.HistorialSimulacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CashFlowRequeridoUsd")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CostoTotalEnDestinoArs")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CostoUnitarioFinalArs")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CotizacionDolarUtilizada")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaSimulacion")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FleteUsd")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IvaCreditoFiscalUsd")
                        .HasColumnType("TEXT");

                    b.Property<string>("SkuProducto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorFobUsd")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HistorialSimulaciones");
                });

            modelBuilder.Entity("MeliManager.Core.Models.Producto", b =>
                {
                    b.Property<string>("Sku")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Alto")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Ancho")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CostoUnitario")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DerechosPorcentaje")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Fob")
                        .HasColumnType("TEXT");

                    b.Property<string>("GaleriaJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Largo")
                        .HasColumnType("TEXT");

                    b.Property<string>("MensajePostVenta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PesoKg")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("TEXT");

                    b.Property<string>("RutaManualPdf")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Sku");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("MeliManager.Core.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ComisionML")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CostoEnvio")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CostoUnitario")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IngresoBruto")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroOrden")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SkuProducto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ventas");
                });
#pragma warning restore 612, 618
        }
    }
}
